### ISSUE TITLE
FirmwareDownload is failing minimum test requirement 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#150]
@rafaellehmkuhl check https://github.com/bluerobotics/companion-docker/actions/runs/726942311

**Comment by rafaellehmkuhl** [comment]
Apparently this is due to problems on the ardupilot firmware servers.
I had this locally already. From time to time it get's down or intermitent.

**Comment by patrickelectric** [comment]
Should we handle it somehow ?

**Comment by rafaellehmkuhl** [comment]
We can move to `urlopen` instead of `urlretrieve` and set a timeout. It's not guaranteed, but it helps with intermittent servers.

A more correct approach would also include separating unit tests from integration tests (this case), so we can easily identify when some test is not passing because of changes/downtime on external resources, instead of local changes.

**Comment by rafaellehmkuhl** [comment]
Also, `urlretrieve` is going to be deprecated in the future, so moving it is would be good.
As we are dealing with small files in this case, there's no problem in moving without more modifications.
