### ISSUE TITLE
Install: Add swapfile for low memory boards

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/companion-docker#68]

**Comment by patrickelectric** [comment]
The installation may get stuck if there is not enough memory available

**Comment by patrickelectric** [comment]
the problem with swap is that can break the sdcard, since the sdcard was not project to a bunch of read/write operations. It's also usually slow. 
Raspbian also comes with a swapfile, but it has a swapness where it's only used is serious emergencies. 
Since mostly raspberries uses at least 1GB of RAM, we should be fine.
